apiVersion: v1
kind: Secret
metadata:
  name: fschallengesecret
  # A bootstrap token Secret usually resides in the kube-system namespace
  namespace: production
type: kubernetes.io/basic-auth
stringData:
  username: MY_SECRET # required field for kubernetes.io/basic-auth
  password: On3H1torL3sS # required field for kubernetes.io/basic-auth
