# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: FSLAB Test AWS CICD

on:
  push:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: configure node JS
      uses: actions/setup-node@v4
      with:
        node-version: 15
        cache: 'npm'
        cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json

    - name: Install
      working-directory: codebase/rdicidr-0.1.0
      run: npm install
    
    - name: ESLint
      working-directory: codebase/rdicidr-0.1.0
      run: npm run lint
    
    - name: prettier
      working-directory: codebase/rdicidr-0.1.0
      run: npm run prettier || true

    - name: test
      working-directory: codebase/rdicidr-0.1.0
      run:  CI=true npm run test

    - name: build
      working-directory: codebase/rdicidr-0.1.0
      run: npm run build --if-present
    
  buildimage:
    name: build docker image
    runs-on: ubuntu-latest
    needs: [build]

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the Docker image
      working-directory: codebase/rdicidr-0.1.0
      run: | 
       echo "${{secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u daniel55247 --password-stdin
       docker build -t ghcr.io/daniel55247/fslabchallenge/fslabimagechallenge:latest .
       docker push ghcr.io/daniel55247/fslabchallenge/fslabimagechallenge:latest

